### ISSUE TITLE
jp2file shows errors when parsing CAI-injected photo in both Py2 and Py3

### ISSUE THREAD

**Issue by bafu** [thorfdbg/codestream-parser#6]
CAI-injected photo for testing: [meimei-fried-chicken-cai-cai-cai.jpg](https://user-images.githubusercontent.com/292790/118789457-6193a200-b8c7-11eb-85ab-6e94a5a9d48d.jpg)

```
$ sha256sum meimei-fried-chicken-cai-cai-cai.jpg 
16eb3e187c2aca2d28ac81979645077bb53693606911e552feb32c3b84cab87d  meimei-fried-chicken-cai-cai-cai.jpg
```

**Steps to Reproduce**

With Python3

```
$ python3 jp2file.py meimei-fried-chicken-cai-cai-cai.jpg 
  File "jp2file.py", line 30
    print "Placeholder box"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Placeholder box")?
```

With Python 2

```
python2 jp2file.py meimei-fried-chicken-cai-cai-cai.jpg
###############################################################
# JP2 file format log file generated by jp2file.py            #
###############################################################

0       : New marker: SOI (Start of image)


2       : New marker: APP1 (Application marker #1)


17296   : New marker: APP1 (Application marker #1)


19749   : New marker: APP11 (JPEG XT Extension Marker)


85286   : New marker: APP11 (JPEG XT Extension Marker)


150823  : New marker: APP11 (JPEG XT Extension Marker)


216360  : New marker: APP11 (JPEG XT Extension Marker)


281897  : New marker: APP11 (JPEG XT Extension Marker)


347434  : New marker: APP11 (JPEG XT Extension Marker)


412971  : New marker: APP11 (JPEG XT Extension Marker)


478508  : New marker: APP11 (JPEG XT Extension Marker)


544045  : New marker: APP11 (JPEG XT Extension Marker)


609582  : New marker: APP11 (JPEG XT Extension Marker)


675119  : New marker: APP11 (JPEG XT Extension Marker)


740656  : New marker: APP11 (JPEG XT Extension Marker)


806193  : New marker: APP11 (JPEG XT Extension Marker)


871730  : New marker: APP11 (JPEG XT Extension Marker)


937267  : New marker: APP11 (JPEG XT Extension Marker)


1002804 : New marker: APP11 (JPEG XT Extension Marker)


1068341 : New marker: APP11 (JPEG XT Extension Marker)


1133878 : New marker: APP11 (JPEG XT Extension Marker)


1199415 : New marker: APP11 (JPEG XT Extension Marker)


1264952 : New marker: APP11 (JPEG XT Extension Marker)


1330489 : New marker: APP11 (JPEG XT Extension Marker)


1396026 : New marker: APP11 (JPEG XT Extension Marker)

    0       : Sub Box: "jumb" JUMBF Box
      8       : Sub Box: "jumd"         JUMBF Description box
        TYPE: 63 61 63 62 00 11 00 10 80 00 00 aa 00 38 9b 71
        TOGGLES: 0b11
        LABEL: cai
        No ID
        No Signature

      37      : Sub Box: "jumb" JUMBF Box
        45      : Sub Box: "jumd"           JUMBF Description box
          TYPE: 63 61 73 74 00 11 00 10 80 00 00 aa 00 38 9b 71
          TOGGLES: 0b11
          LABEL: cb.numbersprotocol_1
          No ID
          No Signature

        91      : Sub Box: "jumb" JUMBF Box
          99      : Sub Box: "jumd"             JUMBF Description box
            TYPE: 63 61 61 73 00 11 00 10 80 00 00 aa 00 38 9b 71
            TOGGLES: 0b11
            LABEL: cai.assertions
            No ID
            No Signature

          139     : Sub Box: "jumb" JUMBF Box
            147     : Sub Box: "jumd"               JUMBF Description box
              TYPE: 6a 73 6f 6e 00 11 00 10 80 00 00 aa 00 38 9b 71
              TOGGLES: 0b11
              LABEL: adobe.asset.info
              No ID
              No Signature

            189     : Sub Box: "json" JSON box
              Data:
              {"title":"meimei-fried-chicken.jpg"}


          233     : Sub Box: "jumb" JUMBF Box
            241     : Sub Box: "jumd"               JUMBF Description box
              TYPE: 6a 73 6f 6e 00 11 00 10 80 00 00 aa 00 38 9b 71
              TOGGLES: 0b11
              LABEL: cai.location.broad
              No ID
              No Signature

            285     : Sub Box: "json" JSON box
              Data:
              {"location":"Dogworld, Taipei Taiwan"}


          331     : Sub Box: "jumb" JUMBF Box
            339     : Sub Box: "jumd"               JUMBF Description box
              TYPE: 6a 73 6f 6e 00 11 00 10 80 00 00 aa 00 38 9b 71
              TOGGLES: 0b11
              LABEL: cai.rights
              No ID
              No Signature

            375     : Sub Box: "json" JSON box
              Data:
              {"copyright":"Tammy Yang"}


          409     : Sub Box: "jumb" JUMBF Box
            417     : Sub Box: "jumd"               JUMBF Description box
              TYPE: 65 79 d6 fb db a2 44 6b b2 ac 1b 82 fe eb 89 d1
              TOGGLES: 0b11
              LABEL: cai.claim.thumbnail.jpg.jpg
              No ID
              No Signature

            470     : Sub Box: "jp2c" Codestream box
Traceback (most recent call last):
  File "jp2file.py", line 2331, in <module>
    jpg.stream_parse(file,0)
  File "/home/bafu/codes/codestream-parser/jpgcodestream.py", line 439, in stream_parse
    self.parse_table()
  File "/home/bafu/codes/codestream-parser/jpgcodestream.py", line 370, in parse_table
    self.parse_APP(ordw(self.buffer) - 0xffe0)
  File "/home/bafu/codes/codestream-parser/jpgcodestream.py", line 323, in parse_APP
    box.parse(self.superhook)
  File "/home/bafu/codes/codestream-parser/jp2box.py", line 156, in parse
    hook(self,id,"%d" % length)
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2130, in superbox_hook
    parse_superbox(box,"JUMBF Box")
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2043, in parse_superbox
    box.parse(superbox_hook)
  File "/home/bafu/codes/codestream-parser/jp2box.py", line 156, in parse
    hook(self,id,"%d" % length)
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2130, in superbox_hook
    parse_superbox(box,"JUMBF Box")
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2043, in parse_superbox
    box.parse(superbox_hook)
  File "/home/bafu/codes/codestream-parser/jp2box.py", line 156, in parse
    hook(self,id,"%d" % length)
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2130, in superbox_hook
    parse_superbox(box,"JUMBF Box")
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2043, in parse_superbox
    box.parse(superbox_hook)
  File "/home/bafu/codes/codestream-parser/jp2box.py", line 156, in parse
    hook(self,id,"%d" % length)
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2130, in superbox_hook
    parse_superbox(box,"JUMBF Box")
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2043, in parse_superbox
    box.parse(superbox_hook)
  File "/home/bafu/codes/codestream-parser/jp2box.py", line 156, in parse
    hook(self,id,"%d" % length)
  File "/home/bafu/codes/codestream-parser/jp2file.py", line 2069, in superbox_hook
    cs = JPGCodestream(indent = box.indent + 1, hook = superbox_hook)
NameError: global name 'JPGCodestream' is not defined
```

**Environment**

* codestream-parser: commit `940fe1d` (current master)
* Python 3: `3.8.2`
* Python 2: `2.7.18`

**Comment by bafu** [comment]
For Python 3, the root cause seems to be that Py3 support PR had been reverted (#5).

For Python 2, the root cause should be the circular import in `jp2file` and `jpgcodestream`:

```python
# jp2file.py
from jpgcodestream import *

# jpgcodestream.py
from jp2file import *
```

**Comment by thorfdbg** [comment]
Yes, indeed. This should hopefully be fixed in the latest version. Could you please pull again and try your luck again - as said, I should have fixed this. Re-open if not.

Thanks,
Thomas

**Comment by bafu** [comment]
I've confirmed that this fix works for Python2. Thanks for sharing, Thomas.
